name: publish

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      #- name: Install parcel
      #  run: |
      #    sudo npm install -g parcel

      - name: Fetch repo info
        run: |
          INFO=$(curl https://api.github.com/repos/femtovg/femtovg)
          RELEASES=$(curl https://api.github.com/repos/femtovg/femtovg/releases)
          echo "{ \"locals\": {\"info\": $INFO, \"releases\": $RELEASES} }" > .pugrc

      - name: Build site
        run: |
          npm install
          npm --version
          node --version
          npx parcel --version
          npx parcel build --public-url "./" index.pug

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: live # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
